// <auto-generated />
using System;
using DumpDrive.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DumpDrive.Data.Migrations
{
    [DbContext(typeof(DumpDriveDbContext))]
    [Migration("20250102140525_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("FileId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangeType = 0,
                            ChangedByUserId = 1,
                            FileId = 1,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ChangeType = 0,
                            ChangedByUserId = 2,
                            FileId = 2,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ChangeType = 1,
                            ChangedByUserId = 3,
                            FileId = 3,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ChangeType = 0,
                            ChangedByUserId = 4,
                            FileId = 4,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ChangeType = 0,
                            ChangedByUserId = 2,
                            FileId = 5,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ChangeType = 1,
                            ChangedByUserId = 3,
                            FileId = 6,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            ChangeType = 0,
                            ChangedByUserId = 1,
                            FileId = 7,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            ChangeType = 0,
                            ChangedByUserId = 3,
                            FileId = 8,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            ChangeType = 1,
                            ChangedByUserId = 4,
                            FileId = 9,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            ChangeType = 0,
                            ChangedByUserId = 5,
                            FileId = 10,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            ChangeType = 0,
                            ChangedByUserId = 6,
                            FileId = 11,
                            Timestamp = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Great resume!",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 895, DateTimeKind.Local).AddTicks(8923),
                            FileId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lovely!",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7333),
                            FileId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Nice!",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7353),
                            FileId = 9,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Cool!",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7358),
                            FileId = 8,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "Could be better.",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7362),
                            FileId = 7,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "Beautiful!",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7376),
                            FileId = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Content = "I dont like this song!",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7380),
                            FileId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Amazing!",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7384),
                            FileId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "Excellent plan!",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7387),
                            FileId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "Great presentation!",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7392),
                            FileId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            Content = "Nice.",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7396),
                            FileId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            Content = "Important archive data.",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7399),
                            FileId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Content = "Data needs cleanup.",
                            CreatedAt = new DateTime(2025, 1, 2, 15, 5, 24, 898, DateTimeKind.Local).AddTicks(7403),
                            FileId = 6,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.DFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("FolderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Some content for resume.pdf",
                            FolderId = 1,
                            LastModified = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "resume.pdf",
                            OwnerId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Content = "Image content for holiday.jpg",
                            FolderId = 2,
                            LastModified = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "holiday.jpg",
                            OwnerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Content = "Audio content for song.mp3",
                            FolderId = 3,
                            LastModified = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "song.mp3",
                            OwnerId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Content = "Video content for movie.mp4",
                            FolderId = 4,
                            LastModified = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "movie.mp4",
                            OwnerId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Content = "Document content for project_plan.docx",
                            FolderId = 5,
                            LastModified = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "project_plan.docx",
                            OwnerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Content = "Presentation content for presentation.pptx",
                            FolderId = 6,
                            LastModified = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "presentation.pptx",
                            OwnerId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Content = "Report content for report.pdf",
                            FolderId = 7,
                            LastModified = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "report.pdf",
                            OwnerId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Content = "Archive content for archive.zip",
                            FolderId = 4,
                            LastModified = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "archive.zip",
                            OwnerId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            Content = "Data content for data.csv",
                            FolderId = 1,
                            LastModified = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "data.csv",
                            OwnerId = 4,
                            Status = 0
                        });
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Documents",
                            OwnerId = 1,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Photos",
                            OwnerId = 2,
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Music",
                            OwnerId = 3,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Videos",
                            OwnerId = 4,
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Projects",
                            OwnerId = 3,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Downloads",
                            OwnerId = 2,
                            Status = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Archives",
                            OwnerId = 1,
                            Status = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.SharedFile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("UserSharedFiles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FileId = 2
                        },
                        new
                        {
                            UserId = 2,
                            FileId = 4
                        },
                        new
                        {
                            UserId = 3,
                            FileId = 6
                        },
                        new
                        {
                            UserId = 4,
                            FileId = 8
                        },
                        new
                        {
                            UserId = 1,
                            FileId = 10
                        },
                        new
                        {
                            UserId = 2,
                            FileId = 12
                        },
                        new
                        {
                            UserId = 3,
                            FileId = 4
                        },
                        new
                        {
                            UserId = 4,
                            FileId = 6
                        });
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.SharedFolder", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("FolderId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "FolderId");

                    b.HasIndex("FolderId");

                    b.ToTable("UserSharedFolders");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FolderId = 2
                        },
                        new
                        {
                            UserId = 2,
                            FolderId = 6
                        },
                        new
                        {
                            UserId = 3,
                            FolderId = 4
                        },
                        new
                        {
                            UserId = 4,
                            FolderId = 8
                        },
                        new
                        {
                            UserId = 1,
                            FolderId = 10
                        },
                        new
                        {
                            UserId = 2,
                            FolderId = 10
                        },
                        new
                        {
                            UserId = 3,
                            FolderId = 2
                        },
                        new
                        {
                            UserId = 4,
                            FolderId = 4
                        });
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ana@gmail.com",
                            Name = "Ana",
                            Password = "pass12345",
                            Surname = "Anic"
                        },
                        new
                        {
                            Id = 2,
                            Email = "marko@gmail.com",
                            Name = "Marko",
                            Password = "pass54322",
                            Surname = "Markic"
                        },
                        new
                        {
                            Id = 3,
                            Email = "josip@gmail.com",
                            Name = "Josip",
                            Password = "qwert",
                            Surname = "Jopic"
                        },
                        new
                        {
                            Id = 4,
                            Email = "pero@gmail.com",
                            Name = "Pero",
                            Password = "pass7",
                            Surname = "Peric"
                        });
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.AuditLog", b =>
                {
                    b.HasOne("DumpDrive.Data.Entities.Models.User", "ChangedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpDrive.Data.Entities.Models.DFile", "File")
                        .WithMany("AuditLogs")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("File");
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.Comment", b =>
                {
                    b.HasOne("DumpDrive.Data.Entities.Models.DFile", "File")
                        .WithMany("Comments")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpDrive.Data.Entities.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.DFile", b =>
                {
                    b.HasOne("DumpDrive.Data.Entities.Models.Folder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpDrive.Data.Entities.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.Folder", b =>
                {
                    b.HasOne("DumpDrive.Data.Entities.Models.Folder", null)
                        .WithMany("SubFolders")
                        .HasForeignKey("FolderId");

                    b.HasOne("DumpDrive.Data.Entities.Models.User", "Owner")
                        .WithMany("Folders")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.SharedFile", b =>
                {
                    b.HasOne("DumpDrive.Data.Entities.Models.DFile", "File")
                        .WithMany("SharedUsers")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpDrive.Data.Entities.Models.User", "User")
                        .WithMany("SharedFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.SharedFolder", b =>
                {
                    b.HasOne("DumpDrive.Data.Entities.Models.Folder", "Folder")
                        .WithMany("SharedUsers")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DumpDrive.Data.Entities.Models.User", "User")
                        .WithMany("SharedFolders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.DFile", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Comments");

                    b.Navigation("SharedUsers");
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.Folder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("SharedUsers");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("DumpDrive.Data.Entities.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Comments");

                    b.Navigation("Folders");

                    b.Navigation("SharedFiles");

                    b.Navigation("SharedFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
